version: '3.4'

services:
  patientapi:
    image: ${DOCKER_REGISTRY-}patientapi
    build:
      context: .
      dockerfile: Patient API/Dockerfile
    depends_on: 
      - db
    ports:
      - "5010:80"
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
